# ============================================================
# DOE Threshold Sweep (Calibration)
# Stage 3c — Threshold Calibration
# ============================================================
#
# Purpose:  Sweeps over lit_threshold, rolling_lit_min, and rolling_obs_min
#           parameter combinations; ranks by absolute error from the official
#           SA electrification target (0.877 population share).
# Inputs:   - Map Data/reliability_outputs_blackmarbler/settlement_day_combined_cov_enriched_*_to_*.parquet
#             (generated by Stage 3 / reliability_panel_build.R — run Stage 3 first)
# Outputs:  - Map Data/reliability_outputs_blackmarbler/doe_calibration_sweep_results.csv
# Run:      Rscript Visualizer/doe_threshold_sweep.R
# ============================================================

rm(list = ls())

suppressPackageStartupMessages({
  library(here)
  library(arrow)
  library(data.table)
  library(readr)
})

# -----------------------------
# CONFIG
# -----------------------------
BASE_PATH <- here::here()
OUT_DIR <- file.path(BASE_PATH, "Map Data", "reliability_outputs_blackmarbler")
PANEL_FILE <- file.path(OUT_DIR, "settlement_day_combined_cov_enriched_2023-01_to_2023-12.parquet")

TARGET_POP_SHARE <- 0.877
END_DATE <- as.Date("2023-12-31")
ROLLING_DAYS <- 30L

# Moonlight filtering before DOE construction.
# none | obvious | maybe
MOONLIGHT_FILTER_MODE <- "none"
MOONLIGHT_DAYS_OBVIOUS <- file.path(
  BASE_PATH, "blackmarbler", "out_vnp46a2_sa_daily", "animations",
  "sa_blackmarble_2023_visually_obvious_contamination_days.txt"
)
MOONLIGHT_DAYS_MAYBE <- file.path(
  BASE_PATH, "blackmarbler", "out_vnp46a2_sa_daily", "animations",
  "sa_blackmarble_2023_maybe_contaminated_days.txt"
)

# Sweep grid (focused around stricter settings after initial calibration run)
LIT_THRESHOLD_GRID <- c(0.30,0.31,0.32,0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.40)
ROLLING_LIT_MIN_GRID <- c(6L, 7L, 8L, 9L, 10L, 11L, 12L, 13L, 14L, 15L, 16L, 17L, 18L, 19L, 20L)
ROLLING_OBS_MIN_GRID <- c(15L,20L, 25L, 30L)

TOP_N_PRINT <- 15L

read_exclude_dates <- function(mode) {
  mode <- tolower(mode)
  if (mode == "none") return(as.Date(character(0)))
  if (!mode %in% c("obvious", "maybe")) stop("MOONLIGHT_FILTER_MODE must be one of: none, obvious, maybe")

  path <- if (mode == "obvious") MOONLIGHT_DAYS_OBVIOUS else MOONLIGHT_DAYS_MAYBE
  if (!file.exists(path)) stop("Missing exclusion list: ", path)
  x <- trimws(readLines(path, warn = FALSE))
  x <- x[nzchar(x)]
  d <- as.Date(x)
  sort(unique(d[!is.na(d)]))
}

if (!file.exists(PANEL_FILE)) stop("Missing panel file: ", PANEL_FILE)

cat("Reading panel:", PANEL_FILE, "\n")
panel <- arrow::read_parquet(
  PANEL_FILE,
  col_select = c("settlement_id", "date", "p_lit_sett", "population")
) |>
  as.data.frame()

setDT(panel)
panel[, settlement_id := as.character(settlement_id)]
panel[, date := as.Date(date)]
panel <- panel[date <= END_DATE]

exclude_dates <- read_exclude_dates(MOONLIGHT_FILTER_MODE)
if (length(exclude_dates) > 0) {
  n_before <- nrow(panel)
  panel <- panel[!date %in% exclude_dates]
  cat("Excluded", length(exclude_dates), "dates | rows:", n_before, "->", nrow(panel), "\n")
}

if (nrow(panel) == 0) stop("Panel is empty after date filtering.")

# Settlement populations for calibration denominator.
pop_dt <- panel[, .(population = population[which(!is.na(population))[1]]), by = settlement_id]
pop_dt[is.na(population), population := 0]
setkey(pop_dt, settlement_id)
pop_total <- pop_dt[, sum(population, na.rm = TRUE)]
n_sett_total <- nrow(pop_dt)

cat("Settlements:", n_sett_total, "| Population total:", format(round(pop_total), big.mark = ","), "\n")

# Build full daily calendar once (matches state-construction logic with missing days retained).
date_min <- panel[, min(date, na.rm = TRUE)]
date_max <- panel[, max(date, na.rm = TRUE)]
calendar <- CJ(settlement_id = pop_dt$settlement_id, date = seq.Date(date_min, date_max, by = "day"), unique = TRUE)
setkey(panel, settlement_id, date)
full <- panel[calendar, on = .(settlement_id, date)]
setorder(full, settlement_id, date)

# n_obs30 does not depend on threshold.
full[, obs_one := as.integer(!is.na(p_lit_sett))]
full[, n_obs30 := rev(frollsum(rev(obs_one), n = ROLLING_DAYS, align = "right")), by = settlement_id]

grid <- CJ(
  lit_threshold = LIT_THRESHOLD_GRID,
  rolling_lit_min = as.integer(ROLLING_LIT_MIN_GRID),
  rolling_obs_min = as.integer(ROLLING_OBS_MIN_GRID),
  unique = TRUE
)

cat("Running sweep combos:", nrow(grid), "\n")

results <- vector("list", nrow(grid))
combo_idx <- 0L

for (lt in LIT_THRESHOLD_GRID) {
  full[, lit_one := as.integer(!is.na(p_lit_sett) & p_lit_sett >= lt)]
  full[, n_lit30 := rev(frollsum(rev(lit_one), n = ROLLING_DAYS, align = "right")), by = settlement_id]

  sub_grid <- grid[lit_threshold == lt]
  for (k in seq_len(nrow(sub_grid))) {
    combo_idx <- combo_idx + 1L
    lm <- sub_grid$rolling_lit_min[k]
    om <- sub_grid$rolling_obs_min[k]

    doe_sett <- full[n_obs30 >= om & n_lit30 >= lm, .(doe = min(date)), by = settlement_id]
    n_sett_doe <- nrow(doe_sett)
    pop_doe <- pop_dt[doe_sett, on = .(settlement_id), sum(population, na.rm = TRUE)]

    share_pop <- if (pop_total > 0) pop_doe / pop_total else NA_real_
    share_sett <- if (n_sett_total > 0) n_sett_doe / n_sett_total else NA_real_

    results[[combo_idx]] <- data.table(
      lit_threshold = lt,
      rolling_lit_min = lm,
      rolling_obs_min = om,
      n_settlements_total = n_sett_total,
      n_settlements_doe1 = n_sett_doe,
      share_settlements_doe1 = share_sett,
      population_total = pop_total,
      population_doe1 = pop_doe,
      share_population_doe1 = share_pop,
      target_population_share = TARGET_POP_SHARE,
      abs_error = abs(share_pop - TARGET_POP_SHARE),
      moonlight_filter_mode = MOONLIGHT_FILTER_MODE,
      excluded_days = length(exclude_dates)
    )
  }
  cat("Completed lit_threshold =", lt, "\n")
}

res <- rbindlist(results)
setorder(res, abs_error, -share_population_doe1)

out_csv <- file.path(
  OUT_DIR,
  paste0(
    "doe_calibration_sweep_",
    format(END_DATE, "%Y-%m-%d"),
    "_",
    MOONLIGHT_FILTER_MODE,
    ".csv"
  )
)
readr::write_csv(as.data.frame(res), out_csv)

cat("\nTop", TOP_N_PRINT, "closest to target", TARGET_POP_SHARE, "\n")
print(res[1:TOP_N_PRINT])
cat("\nBest combo:\n")
print(res[1])
cat("\nSaved:", out_csv, "\n")
