# ============================================================
# Reliability Leaflet Map (Interactive)
# Stage 6 — Interactive Visualisation
# ============================================================
#
# Purpose:  Renders an interactive Leaflet HTML map showing yearly
#           electrification reliability per settlement, overlaid with
#           power generators, the national electricity grid, and admin
#           boundaries.
# Inputs:   - Map Data/Settlements/GPKG/south_africa_dre_atlas_settlements_simplified_full_col.gpkg
#           - Map Data/reliability_outputs_blackmarbler/settlement_reliability_yearly_strict_yearlykeep_postdoe.parquet
#             (generated by Stage 3b / reliability_panel_build_yearlykeep.R — run Stage 3b first)
#           - Map Data/Generators Data/generators_outputs/south_africa_power_plants.gpkg
#           - Map Data/Grid Data/electricitygrid_Africa_JRC/output_folder/electricity_grid_south_africa.gpkg
#           - Map Data/Boundaries/boundaries_outputs/south_africa_admin_boundaries_GADM.gpkg
# Outputs:  - leaflet_reliability_yearly.html
# Run:      Rscript Visualizer/reliability_leaflet_map.R
# ============================================================

rm(list = ls())

suppressPackageStartupMessages({
  library(here)
  library(sf)
  library(dplyr)
  library(arrow)
  library(leaflet)
  library(htmlwidgets)
  library(htmltools)
  library(stringr)
})

sf::sf_use_s2(FALSE)

# -----------------------------
# PATHS
# -----------------------------
BASE_PATH <- here::here()

RELIABILITY_PARQUET <- file.path(BASE_PATH, "Map Data", "reliability_outputs_blackmarbler",
  "settlement_reliability_yearly_strict_yearlykeep_postdoe.parquet")

STATES_PARQUET <- file.path(BASE_PATH, "Map Data", "reliability_outputs_blackmarbler",
  "settlement_day_states_strict_yearlykeep.parquet")

SETT_SIMPL_GPKG <- file.path(BASE_PATH, "Map Data", "Settlements", "GPKG",
  "south_africa_dre_atlas_settlements_simplified_full_col.gpkg")

GENERATORS_GPKG <- file.path(BASE_PATH, "Map Data", "Generators Data", "generators_outputs",
  "south_africa_power_plants.gpkg")
GEN_LAYER <- "generators_sa"

BOUNDARIES_GPKG <- file.path(BASE_PATH, "Map Data", "Boundaries", "boundaries_outputs",
  "south_africa_admin_boundaries_GADM.gpkg")
BND_LAYER_ADMIN0 <- "admin0_country"

GRID_GPKG <- file.path(BASE_PATH, "Map Data", "Grid Data", "electricitygrid_Africa_JRC",
  "output_folder", "electricity_grid_south_africa.gpkg")
GRID_LAYER <- "grid_sa"

OUT_HTML <- file.path(BASE_PATH, "leaflet_reliability_yearly.html")

# -----------------------------
# HELPERS
# -----------------------------
fmt_num <- function(x, digits = 1) {
  ifelse(is.na(x), "NA", formatC(as.numeric(x), format = "f", digits = digits))
}

fmt_int <- function(x) {
  x <- suppressWarnings(as.numeric(x))
  ifelse(is.na(x), "NA", formatC(x, format = "d", big.mark = ","))
}

s <- function(x) {
  x <- as.character(x)
  ifelse(is.na(x) | !nzchar(x), "NA", htmlEscape(x))
}

fuel_color <- function(fuel) {
  f <- tolower(trimws(as.character(fuel)))
  f[is.na(f) | f == ""] <- "unknown"

  dplyr::case_when(
    grepl("coal", f)                      ~ "#1F1F1F",
    grepl("gas", f)                       ~ "#4d4d4d",
    grepl("oil|diesel", f)                ~ "#8C510A",
    grepl("nuclear", f)                   ~ "#7B3294",
    grepl("hydro", f)                     ~ "#2C7FB8",
    grepl("wind", f)                      ~ "#41AB5D",
    grepl("solar", f)                     ~ "#00A087",
    grepl("bio|biomass|biogas|waste", f)  ~ "#6B8E23",
    TRUE                                  ~ "#6E6E6E"
  )
}

# -----------------------------
# 1) READ RELIABILITY PARQUET
# -----------------------------
if (!file.exists(RELIABILITY_PARQUET)) {
  stop("Stage 3b output not found: ", RELIABILITY_PARQUET,
       "\nRun Visualizer/reliability_panel_build_yearlykeep.R first.")
}
cat("Reading reliability parquet...\n")
rel <- read_parquet(RELIABILITY_PARQUET)

cat("Computing annual dark-day counts from states...\n")
dark_annual <- read_parquet(
  STATES_PARQUET,
  col_select = c("settlement_id", "dark_day")
) %>%
  group_by(settlement_id) %>%
  summarise(n_dark_days_annual = sum(dark_day, na.rm = TRUE), .groups = "drop") %>%
  mutate(settlement_id = as.character(settlement_id))

# -----------------------------
# 2) READ SETTLEMENT GEOMETRIES
# -----------------------------
cat("Reading settlement geometries...\n")
sett <- st_read(SETT_SIMPL_GPKG, quiet = TRUE) %>%
  st_make_valid()

# Left-join reliability metrics onto settlement geometry (coerce key to character)
map_sf <- sett %>%
  mutate(settlement_id = as.character(settlement_id)) %>%
  left_join(
    rel %>%
      mutate(settlement_id = as.character(settlement_id)) %>%
      select(settlement_id, uptime, dark_share, mean_p_lit,
             n_days_obs, cv_p_lit, mean_coverage),
    by = "settlement_id"
  ) %>%
  left_join(dark_annual, by = "settlement_id") %>%
  st_transform(4326)

# -----------------------------
# SETTLEMENT POPUP
# -----------------------------
popup_settlement <- function(df) {
  paste0(
    "<div style='font-size:13px; line-height:1.5; min-width:240px;'>",

    "<div style='font-size:15px; font-weight:bold; margin-bottom:6px;'>",
    s(df$village_name),
    "</div>",

    "<b>Yearly uptime:</b> ",           fmt_num(df$uptime, 3),         "<br>",
    "<b>Dark share:</b> ",              fmt_num(df$dark_share, 3),      "<br>",
    "<b>CV radiance (volatility):</b> ", fmt_num(df$cv_p_lit, 3),      "<br>",
    "<b>Days observed:</b> ",           fmt_int(df$n_days_obs),         "<br>",
    "<b>Dark days (full year):</b> ",   fmt_int(df$n_dark_days_annual), "<br>",
    "<b>Mean p<sub>lit</sub>:</b> ",    fmt_num(df$mean_p_lit, 3),      "<br>",
    "<b>Mean pixel coverage:</b> ",     fmt_num(df$mean_coverage, 2),   "<br><br>",

    "<b>Population:</b> ",              fmt_int(df$population),         "<br>",
    "<b>Building density:</b> ",        s(df$building_density_percent), "<br>",
    "<b>Demand (kWh/day):</b> ",        fmt_num(df$demand, 1),          "<br><br>",

    "<b>Province:</b> ",  s(df$admin_cgaz_1), "<br>",
    "<b>District:</b> ",  s(df$admin_cgaz_2),

    "</div>"
  )
}

cat("Building settlement popups...\n")
map_sf$popup_html <- vapply(seq_len(nrow(map_sf)),
  function(i) popup_settlement(map_sf[i, ]), character(1))

# -----------------------------
# 3) READ SOUTH AFRICA BORDER
# -----------------------------
cat("Reading SA border...\n")
sa0 <- st_read(BOUNDARIES_GPKG, layer = BND_LAYER_ADMIN0, quiet = TRUE) %>%
  st_make_valid() %>%
  st_transform(4326)

# -----------------------------
# 4) READ GENERATORS
# -----------------------------
cat("Reading generators...\n")
gen_ll <- st_read(GENERATORS_GPKG, layer = GEN_LAYER, quiet = TRUE) %>%
  st_make_valid() %>%
  st_transform(4326)

col_name  <- if ("plant_name"   %in% names(gen_ll)) "plant_name"   else if ("name"  %in% names(gen_ll)) "name"  else NA_character_
col_fuel  <- if ("fuel_or_tech" %in% names(gen_ll)) "fuel_or_tech" else if ("fuel"  %in% names(gen_ll)) "fuel"  else NA_character_
col_stat  <- if ("status"       %in% names(gen_ll)) "status"       else NA_character_
col_cap   <- if ("capacity_mw"  %in% names(gen_ll)) "capacity_mw"  else NA_character_
col_owner <- if ("owner"        %in% names(gen_ll)) "owner"        else NA_character_
col_tech  <- if ("technology"   %in% names(gen_ll)) "technology"   else NA_character_
col_start <- if ("start_year"   %in% names(gen_ll)) "start_year"   else NA_character_
col_type  <- if ("type"         %in% names(gen_ll)) "type"         else NA_character_

gen_ll$fuel_val <- if (!is.na(col_fuel)) as.character(gen_ll[[col_fuel]]) else NA_character_
gen_ll$mk_col   <- fuel_color(gen_ll$fuel_val)

gen_ll$popup_html <- vapply(seq_len(nrow(gen_ll)), function(i) {
  r     <- gen_ll[i, ]
  nm    <- if (!is.na(col_name))  as.character(r[[col_name]])  else "Power plant"
  fuel  <- if (!is.na(col_fuel))  as.character(r[[col_fuel]])  else "Unknown"
  stat  <- if (!is.na(col_stat))  as.character(r[[col_stat]])  else "Unknown"
  cap   <- if (!is.na(col_cap))   suppressWarnings(as.numeric(r[[col_cap]])) else NA_real_
  owner <- if (!is.na(col_owner)) as.character(r[[col_owner]]) else NA_character_
  tech  <- if (!is.na(col_tech))  as.character(r[[col_tech]])  else NA_character_
  sy    <- if (!is.na(col_start)) as.character(r[[col_start]]) else NA_character_
  typ   <- if (!is.na(col_type))  as.character(r[[col_type]])  else NA_character_

  dot <- fuel_color(fuel)

  extra_lines <- character(0)
  if (!is.na(typ)   && nzchar(typ))   extra_lines <- c(extra_lines, paste0("<b>Type:</b> ",        htmlEscape(typ)))
  if (!is.na(owner) && nzchar(owner)) extra_lines <- c(extra_lines, paste0("<b>Owner:</b> ",       htmlEscape(owner)))
  if (!is.na(tech)  && nzchar(tech))  extra_lines <- c(extra_lines, paste0("<b>Technology:</b> ",  htmlEscape(tech)))
  if (!is.na(sy)    && nzchar(sy))    extra_lines <- c(extra_lines, paste0("<b>Start year:</b> ",  htmlEscape(sy)))

  paste0(
    "<div style='font-family: system-ui,-apple-system,Segoe UI,Roboto,Arial; font-size:14px; line-height:1.45; min-width:260px;'>",
    "<div style='font-size:18px; font-weight:800; letter-spacing:1px; text-transform:uppercase; margin-bottom:10px;'>",
    htmlEscape(nm),
    "</div>",
    "<div style='margin-bottom:6px;'>",
    "<b>Fuel/Tech:</b> ",
    "<span style='display:inline-block;width:10px;height:10px;border-radius:50%;background:", dot, ";margin:0 8px 0 6px;'></span>",
    htmlEscape(fuel),
    "</div>",
    "<div style='margin-bottom:6px;'><b>Status:</b> ", htmlEscape(stat), "</div>",
    "<div style='margin-bottom:10px;'><b>Capacity:</b> ",
    ifelse(is.na(cap), "NA", paste0(fmt_num(cap, 1), " MW")),
    "</div>",
    if (length(extra_lines) > 0) paste0(paste0(extra_lines, collapse = "<br>"), "<br>") else "",
    "</div>"
  )
}, character(1))

# -----------------------------
# 5) READ GRID
# -----------------------------
cat("Reading grid...\n")
grid_sa <- st_read(GRID_GPKG, layer = GRID_LAYER, quiet = TRUE) %>%
  st_make_valid() %>%
  st_transform(4326)

# -----------------------------
# 6) BUILD LEAFLET MAP
# -----------------------------
cat("Building Leaflet map...\n")

pal <- leaflet::colorNumeric(
  palette  = colorRampPalette(c("#5e0000", "#b30000", "#e34a33", "#fc8d59", "#fed976"))(256),
  domain   = c(0, 1),
  na.color = "#e0e0e0"
)

GRID_COL <- "#08306B"

map <- leaflet(options = leafletOptions(preferCanvas = TRUE)) %>%

  addProviderTiles(providers$CartoDB.Positron,        group = "Basemap (Light)") %>%
  addProviderTiles(providers$Esri.WorldImagery,        group = "Satellite") %>%
  addProviderTiles(providers$CartoDB.PositronOnlyLabels, group = "Labels") %>%

  addPolygons(
    data         = map_sf,
    group        = "Settlements (yearly uptime)",
    fillColor    = ~pal(uptime),
    fillOpacity  = 0.75,
    color        = NA,
    weight       = 0,
    smoothFactor = 0.2,
    popup        = ~popup_html
  ) %>%

  addPolylines(
    data         = grid_sa,
    group        = "Grid (South Africa)",
    color        = GRID_COL,
    weight       = 1.0,
    opacity      = 0.55,
    smoothFactor = 1
  ) %>%

  addPolylines(
    data    = sa0,
    group   = "South Africa border",
    color   = "#000000",
    weight  = 1.2,
    opacity = 0.85
  ) %>%

  addCircleMarkers(
    data        = gen_ll,
    group       = "Power plants",
    radius      = 4.5,
    stroke      = TRUE,
    weight      = 1.2,
    opacity     = 0.9,
    color       = "#FFFFFF",
    fillOpacity = 0.95,
    fillColor   = ~mk_col,
    popup       = ~popup_html
  ) %>%

  addLayersControl(
    baseGroups = c("Basemap (Light)", "Satellite"),
    overlayGroups = c(
      "Labels",
      "Settlements (yearly uptime)",
      "Grid (South Africa)",
      "South Africa border",
      "Power plants"
    ),
    options = layersControlOptions(collapsed = FALSE)
  ) %>%

  addLegend(
    position = "topright",
    pal      = pal,
    values   = map_sf$uptime,
    title    = "Yearly uptime",
    opacity  = 1
  ) %>%

  setView(lng = 24.5, lat = -29.0, zoom = 5)

# -----------------------------
# 7) SAVE HTML
# -----------------------------
cat("Saving HTML...\n")
htmlwidgets::saveWidget(map, OUT_HTML, selfcontained = TRUE)
cat("Saved:", OUT_HTML, "\n")
